# Generated by Django 4.0.6 on 2022-07-27 07:14

from django.db import migrations, models
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_managers_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtendsWithBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('fist_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-email')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Phone Number')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is Admin?')),
                ('is_active', models.BooleanField(default=True, verbose_name='is Active?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
