# Generated by Django 4.0.6 on 2022-07-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userextendswithbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userextendswithbase',
            options={'verbose_name': 'Base User', 'verbose_name_plural': 'Base Users'},
        ),
        migrations.RemoveField(
            model_name='userextendswithbase',
            name='is_active',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=35, verbose_name='Item Name')),
                ('item_code', models.CharField(blank=True, max_length=35, null=True)),
                ('item_price', models.IntegerField(default=0)),
                ('item_qty', models.IntegerField(default=0)),
                ('item_remaining_qty', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.itemcategory')),
            ],
        ),
    ]
