# Generated by Django 4.0.6 on 2022-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdb',
            name='zip_code',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
