# Generated by Django 4.0.6 on 2022-08-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_itemcategory_item'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
