# Generated by Django 4.0.6 on 2022-07-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_itemcategory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_discounted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
