# Generated by Django 4.0.6 on 2022-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testdb_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdb',
            name='country',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
