# Generated by Django 4.0.6 on 2022-07-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_itemcategory_alter_userextendswithbase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, editable=False, max_length=35, null=True),
        ),
    ]
